# Generated by Django 2.1 on 2018-08-22 00:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 numbers', regex='\\d{11}')])),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('cancel_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funding',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='cancel_at',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='username',
        ),
        migrations.AddField(
            model_name='funding',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='reward.FundingOrder'),
            preserve_default=False,
        ),
    ]
